

class Exception:
    @classmethod
    def not_found_exceptions():
        pass